# Generated by Django 6.0.3 on 2026-05-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('exam', models.CharField(max_length=50)),
                ('aadhaar', models.FileField(upload_to='aadhaar/')),
                ('marksheet', models.FileField(upload_to='marksheets/')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('signature', models.ImageField(upload_to='signatures/')),
            ],
        ),
    ]
