# Generated by Django 6.0.5 on 2026-05-15 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_is_verified_student_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='exam',
            field=models.CharField(choices=[('Police', 'Police'), ('Army', 'Army'), ('SSC', 'SSC'), ('Banking', 'Banking'), ('Railway', 'Railway'), ('UPSC', 'UPSC')], max_length=50),
        ),
    ]
