# Generated by Django 6.0.5 on 2026-05-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_exam'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='is_verified',
            new_name='bpl',
        ),
        migrations.RemoveField(
            model_name='student',
            name='otp',
        ),
        migrations.AddField(
            model_name='student',
            name='irdp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='physical_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='undertaking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='widow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='exam',
            field=models.CharField(choices=[('HP Police', 'HP Police'), ('SSC', 'SSC'), ('Army', 'Army'), ('Home Guard', 'Home Guard'), ('Railway', 'Railway'), ('Banking', 'Banking')], max_length=50),
        ),
    ]
