# Generated by Django 6.0.5 on 2026-05-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_is_verified_student_bpl_remove_student_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='training_type',
            field=models.CharField(default='Written', max_length=50),
        ),
    ]
